apimanager/urls.py
from django.conf.urls import include, url

urlpatterns = (
    url(r'pre_login/$', 'apimanager.views.pre_login_view', name='pre_login'),
    url(r'add/$', 'apimanager.views.add_application', name='add_application'),
    url(r'update/(.*)/$', 'apimanager.views.update_application', name='update_application'),
    url(r'apps/$', 'apimanager.views.view_applications', name='view_applications'),
)

docs/urls.py
from django.conf.urls import url

from .views import doc_view

urlpatterns = [
    url(r'(?P<path>.*)', doc_view, name='doc_view'),
]

heldev/urls.py
import blog, blog.views
from django.conf.urls import include, url
from django.conf import settings
from django.contrib import admin

from wagtail.wagtailadmin import urls as wagtailadmin_urls
from wagtail.wagtaildocs import urls as wagtaildocs_urls
from wagtail.wagtailcore import urls as wagtail_urls
from django.views.generic import TemplateView
from django.shortcuts import redirect
from django.conf import settings

import projects.views
import github.views
import events.views

def redirect_to_sso(request):
    """
    Bypass traditional Django login by redirecting to SSO server
    If GET has next argument, that will be added to redirect

    :param request: Django request
    :return: HttpResponseRedirect
    """

    if request.GET.get('next'):
        sso_url = settings.AUTH_SSO_URL + '&next={}'.format(request.GET.get('next'))
    else:
        sso_url = settings.AUTH_SSO_URL

    return redirect(sso_url)

urlpatterns = [
    url(r'^django-admin/', include(admin.site.urls)),

    url(r'^accounts/login/$', redirect_to_sso, name='redirect_to_sso'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(wagtailadmin_urls)),
    url(r'^documents/', include(wagtaildocs_urls)),
    url(r'^blog/', include('blog.urls', namespace="blog")),
    url(r'^blog/feed/$', blog.views.LatestEntriesFeed(), name='latest_entries_feed'),
    url(r'^search/$', 'search.views.search', name='search'),
    url(r'^api/', include('apimanager.urls', namespace="apimanager")),
    # client endpoints for external API data
    url(r'^piwik_data/(.*)', projects.views.piwik_data),
    url(r'^uptime_data/(.*)', projects.views.uptime_data),
    url(r'^kpi_data/(.*)', projects.views.kpi_data),
    url(r'^github_data/', github.views.github_data),
    url(r'^event_data/', events.views.event_data),
    # API endpoints
    url(r'^projects/projects.csv', projects.views.cfapi_list),
    url(r'^docs/', include('docs.urls')),
    # wagtail handles the rest
    url(r'', include(wagtail_urls)),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    from django.views.generic import TemplateView

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apimanager/models.py
from django.db import models
from django.conf import settings
from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailadmin.edit_handlers import FieldPanel
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel
from wagtail.wagtailsearch import index
from . import manager


class APIPage(Orderable, Page):
    name = models.CharField("Short and unique identifier for API", max_length=300, blank=False, null=False, unique=True)
    use_api_gateway = models.BooleanField(default=False, help_text="Set to false for APIs not managed by the api.hel.fi API gateway.")
    api_path = models.CharField("Root path for API Management platform", max_length=50, default="", blank=True, null=True,
                                help_text="Actual public API root endpoint; example usage: api.hel.fi/{path}/")
    api_url = models.URLField(blank=False, null=False)
    documentation = models.URLField(blank=True)
    short_description = models.TextField(blank=False)
    full_description = RichTextField(blank=True)
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )

    search_fields = Page.search_fields + (
        index.SearchField('name'),
        index.SearchField('api_url'),
        index.SearchField('short_description'),
        index.SearchField('full_description'),
    )

    content_panels = Page.content_panels + [
        FieldPanel('name'),
        FieldPanel('api_url'),
        FieldPanel('use_api_gateway'),
        FieldPanel('api_path'),
        FieldPanel('documentation'),
        ImageChooserPanel('image'),
        FieldPanel('short_description', classname="full"),
        FieldPanel('full_description', classname="full")
    ]

    def has_swagger_docs(self):
        if not self.documentation:
            return False
        for ext in ('.yaml', '.yml'):
            if self.documentation.endswith(ext):
                return True
        return False

class APIIndexPage(Page):
    subpage_types = ['apimanager.ApiPage']

    def apis(self):
        return APIPage.objects.live().order_by('title')


class KongAPIConfiguration(models.Model):
    api_page = models.OneToOneField(APIPage)
    request_host = models.CharField('Host and domain name', max_length=150,
                                    unique=True,
                                    help_text="Kong requires that API has a unique host name,"
                                              " f.x. name.api.hel.fi -> api.hel.fi/name")
    kong_api_id = models.CharField(max_length=300, editable=False, null=True)

    def __str__(self):
        return u'Configuration for ' + self.api_page.name

    def save_to_kong(self, enable_key_auth=False):
        """
        Create or update API configuration in Kong

        :param enable_key_auth: to enable key auth for API
        :type enable_key_auth: str
        :return: None
        :rtype: None
        """
        
        # NOTE: API kongfiguration now elsewhere
        return None

        existing = manager.check_api(self.kong_api_id)

        if self.request_host.startswith('/'):
            path = self.request_host
            host = None
            strip_request_path = True
            preserve_host=True
        else:
            path = None
            host = self.request_host
            strip_request_path = False
            preserve_host=False

        if existing:
            res = manager.update_api(api_id=self.kong_api_id,
                                     name=self.api_page.name,
                                     upstream_url=self.api_page.api_path,
                                     request_host=host,
                                     request_path=path,
                                     strip_request_path=strip_request_path,
                                     preserve_host=preserve_host)
            self.kong_api_id = res['id']
        else:
            res = manager.create_api(name=self.api_page.name,
                                     upstream_url=self.api_page.api_path,
                                     request_host=host,
                                     request_path=path,
                                     strip_request_path=strip_request_path,
                                     preserve_host=preserve_host)
            self.kong_api_id = res['id']
            self.save()

        if enable_key_auth:
            manager.enable_plugin(self.api_page.name, manager.PLUGINS['key'])


class Application(models.Model):
    """
    Individual application for the API customer
    containing one Kong consumer and its API key
    """
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    subscriptions = models.ManyToManyField(KongAPIConfiguration, through='APISubscription')
    name = models.CharField(max_length=300)
    description = models.TextField(blank=True, null=True)
    app_url = models.URLField(blank=True, null=True)

    def __str__(self):
        return u'Application of ' + self.user.username

import uuid
class APISubscription(models.Model):
    api = models.ForeignKey(KongAPIConfiguration)
    application = models.ForeignKey(Application)
    consumer_id = models.CharField(max_length=300, blank=True, null=True)
    consumer_kong_id = models.CharField(max_length=300, blank=True, null=True)
    key = models.CharField(max_length=300, blank=True, null=True)
    key_kong_id = models.CharField(max_length=300, blank=True, null=True)

    def save(self, *args, **kwargs):
        consumer = uuid.uuid4()
        key = uuid.uuid4()
        self.consumer_id = consumer
        self.consumer_kong_id = consumer
        self.key = key
        self.key_kong_id = key
        super().save(*args, **kwargs)

    def __str__(self):
        return u'API subscription for ' + self.api.api_page.name

    def add_consumer(self):
        """
        Add consumer to Kong for this APISubscription using username
        and subscription id
        """
        if self.consumer_kong_id:
            consumer = manager.get_consumer(self.consumer_kong_id)
            if consumer:
                return True
        res = manager.add_consumer(self.application.user.username + '_' + str(self.pk))
        if res:
            self.consumer_id = self.application.user.username + '_' + str(self.pk)
            self.consumer_kong_id = res['id']
            self.save()
        return True

    def get_api_key(self):
        """
        Register API key in Kong for this subscription using
        its consumer id
        """
        res = manager.request_api_key(self.consumer_kong_id)
        if res:
            self.key = res['key']
            self.key_kong_id = res['id']
            self.save()

    def delete_consumer(self):
        """
        Delete subscription's Consumer from Kong
        :return: None
        """
        manager.delete_consumer(self.consumer_id, cid=self.consumer_kong_id)

    def delete_api_key(self):
        """
        Delete API key from Kong
        :return: None
        """
        manager.delete_api_key(self.consumer_kong_id, self.key_kong_id)

projects/models.py
import json, requests
from collections import OrderedDict
from taggit.models import TaggedItemBase, Tag
from modelcluster.contrib.taggit import ClusterTaggableManager

from django.db import models
from django.core.cache import cache
from django.conf import settings
from django.utils.text import slugify

from wagtail.wagtailcore.models import Page, Orderable
from wagtail.wagtailcore.fields import RichTextField
from wagtail.wagtailadmin.edit_handlers import FieldPanel, InlinePanel
from wagtail.wagtailimages.models import Image
from wagtail.wagtailimages.edit_handlers import ImageChooserPanel
from wagtail.wagtailsnippets.models import register_snippet
from wagtail.wagtailsearch import index

from modelcluster.fields import ParentalKey


class ProjectPageTag(TaggedItemBase):
    content_object = ParentalKey('ProjectPage', related_name='tagged_items')


@register_snippet
class ProjectTag(Tag):
    class Meta:
        proxy = True


class ProjectPage(Orderable, Page):
    STATUSES = (
        ('discovery', 'Discovery'),
        ('alpha', 'Alpha'),
        ('beta', 'Beta'),
        ('live', 'LIVE'),
        ('retirement', 'Retirement')
    )
    tags = ClusterTaggableManager(through=ProjectPageTag, blank=True)
    short_description = models.TextField()
    full_description = RichTextField(blank=True)
    image = models.ForeignKey(
        'wagtailimages.Image',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name='+',
    )
    status = models.CharField(max_length=20, choices=STATUSES, default='discovery')
    piwik_id = models.IntegerField(blank=True, null=True)
    uptimerobot_name = models.CharField(blank=True, null=True, max_length=100)

    def save(self, *args, **kwargs):
        if not self.title:
            if self.project:
                self.title = self.project.name
        return super().save(*args, **kwargs)

    search_fields = Page.search_fields + (
        index.SearchField('short_description'),
        index.SearchField('full_description'),
    )

    content_panels = Page.content_panels + [
        FieldPanel('status'),
        FieldPanel('tags'),
        FieldPanel('short_description'),
        FieldPanel('full_description'),
        ImageChooserPanel('image'),
        FieldPanel('piwik_id'),
        FieldPanel('uptimerobot_name'),
        InlinePanel('dynamic_kpis', label="Dynamic key performance indicators"),
        InlinePanel('kpis', label="Key performance indicators"),
        InlinePanel('roles', label="Roles"),
        InlinePanel('links', label="Links"),
    ]

    def piwik_data(self):
        data = cache.get('piwik_' + slugify(self.title))
        if not data and self.piwik_id:
            response = requests.get(
                'https://analytics.hel.ninja/piwik/?idSite=' +
                str(self.piwik_id) +
                '&module=API&period=day&date=last30&method=VisitsSummary.get&format=json&token_auth=' +
                settings.PIWIK_API_TOKEN)
            if response.status_code == 200:
                # piwik_id was valid
                data = response.text
                # data = json.loads(response.text, object_pairs_hook=OrderedDict)
                cache.add('piwik_' + slugify(self.title), data, 3600)
        return data

    def kpi_data(self):
        data = cache.get('kpis_' + slugify(self.title))
        if not data and self.dynamic_kpis.count():
            data = {}
            for kpi in self.dynamic_kpis.all():
                response = requests.get(kpi.object_count_url)
                if response.status_code == 200:
                    json_data = response.json()
                    for key in kpi.object_count_field_name.split('.'):
                        json_data = json_data[key]
                    data[kpi.object_name] = json_data
            # coffeescript wants the data in json
            data = json.dumps(data)
            cache.add('kpis_' + slugify(self.title), data, 3600)
        return data

    def uptime_data(self):
        complete_data = cache.get('uptime')
        if not complete_data and self.uptimerobot_name:
            response = requests.get(
                'https://api.uptimerobot.com/getMonitors?apiKey=' +
                settings.UPTIMEROBOT_API_TOKEN +
                '&format=json&noJsonCallback=1')
            if response.status_code == 200:
                # returns all monitors, we still have to check for matching name
                complete_data = response.json()
                cache.add('uptime', complete_data, 3600)
        try:
            data = [single_data for single_data in
                    complete_data['monitors']['monitor'] if
                    single_data['friendlyname'] == self.uptimerobot_name][0]
            # coffeescript wants the data in json
            data = json.dumps(data)
        # if name doesn't match, return None
        except (IndexError, TypeError, KeyError):
            data = None
        return data


class ProjectRoleType(Orderable, models.Model):
    name = models.CharField(max_length=50)

    def __lt__(self, other):
        if self.sort_order is None:
            return True
        if other.sort_order is None:
            return False
        return int(self.sort_order).__lt__(int(other.sort_order))

    def __str__(self):
        return self.name


class ProjectRole(models.Model):
    TYPES = (
        ('service_manager', 'Service manager'),
        ('tech', 'Tech lead'),
    )
    project = ParentalKey('projects.ProjectPage', related_name='roles')
    type = models.ForeignKey(ProjectRoleType, related_name='roles')
    person = ParentalKey('aboutus.PersonPage', related_name='roles')

    def __str__(self):
        return "%s as %s for %s" % (self.person, self.type, self.project.title)

    class Meta:
        ordering = ('type',)


class ProjectKPI(models.Model):
    project = ParentalKey('projects.ProjectPage', related_name='kpis')
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=200, null=True, blank=True)
    value = models.CharField(max_length=200)


class ProjectObjectCount(models.Model):
    """
    This model allows dynamic KPI data, fetching number of objects at any API endpoint
    """
    project = ParentalKey('projects.ProjectPage', related_name='dynamic_kpis')
    object_name = models.CharField(max_length=40)
    description = models.CharField(max_length=200, null=True, blank=True)
    object_count_url = models.URLField()
    object_count_field_name = models.CharField(default='meta.count', max_length=40)

    def _str__(self):
        return self.object_name

class ProjectLink(models.Model):
    TYPES = (
        ('main', 'Main'),
        ('github', 'GitHub'),
    )

    project = ParentalKey('projects.ProjectPage', related_name='links')
    type = models.CharField(max_length=20, choices=TYPES)
    public = models.BooleanField(default=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    url = models.URLField()

    def __str__(self):
        return "{0} / {1}".format(str(self.project), self.type)


class ProjectIndexPage(Page):
    subpage_types = ['projects.ProjectPage']

    def projects(self):
        return ProjectPage.objects.live()

    def top_projects(self):
        return self.projects()[:5]

apimanager/templates/apimanager/api_app_list.html
{% extends "base.html" %}
{% load wagtailcore_tags home_tags %}
{% block content %}
<div class="layout-page-content--full">
  <div class="page-content">
    <div class="page-content__box">
            <h1 class="page-section-header">Applications</h1>
            <p>
                <a href="{% url "apimanager:add_application" %}" class="button">Register an application!</a>
            </p>
        {% if apps %}
        <h1>Your applications</h1>
            <ul>
                {%  for app in apps %}
                    <h3><a href="{% url "apimanager:update_application" app.pk %}">{{ app.name }}</a></h3>
                    {% if app.app_url %}
                        <p><a href="{{ app.app_url }}">{{ app.app_url }}</a></p>
                    {% endif %}
                    <p>{{ app.description }}</p>
                    {% if app.apisubscription_set.exists %}
                        <h4>Subscriptions</h4>
                        <ul>
                        {% for sub in app.apisubscription_set.all %}
                            <li>
                                <h5>
                                    <a href="{% pageurl sub.api.api_page %}">{{ sub.api.api_page.name }}</a>
                                </h5>
                                <div>API Key: {{ sub.key }}</div>
                            </li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                {% endfor %}
            </ul>
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}

apimanager/templates/apimanager/api_formi.html
{% extends "base.html" %}
{% load wagtailcore_tags %}

{# Load the tag library #}
{% load bootstrap3 %}

{% block extra_css %}{# Load CSS and JavaScript #}

    {% bootstrap_javascript %}
{%  endblock %}

{% block content %}
<div class="layout-page-content--full">
    <div class="page-content">
        <div class="page-content__box">
        <p>
            <a href="{% url "apimanager:view_applications" %}">Back</a>
        </p>
            <h1>Application register</h1>
            <p>
                By registering your application, you can subscribe to <b>our Open APIs</b> and receive <b>API keys</b>.</p>
            <p>

            {% if app %}
            <form action="{% url "apimanager:update_application" app.pk %}" method="post">
            {% else %}
            <form action="{% url "apimanager:add_application" %}" method="post" class="form">
            {% endif %}
            {% csrf_token %}
            <table>
                {% bootstrap_form form %}
            </table>
            {% buttons %}
                <button type="submit" class="btn btn-primary" name="save" value="Save">
                  {% bootstrap_icon "star" %} Submit
                </button>
            {% endbuttons %}

            {% if subscriptions %}
            <h2>Existing subscriptions</h2>
            <ul>
            {% for sub in subscriptions %}
                <li><button type="submit" name="unsubscribe"  value="{{ sub.pk }}">Unsubscribe from {{ sub.api.api_page.name }}</button></li>
            {% endfor %}
            </ul>
            {%  endif %}
            </form>
        </div>
    </div>
</div>
{% endblock %}

apimanager/templates/apimanager/api_index_page.html
{% extends "base.html" %}
{% load wagtailcore_tags wagtailimages_tags static %}

{% block content %}
{% with apis=self.apis %}
<div class="layout-page-content--full">
      <div class="layout-page-header--full">
        <div class="page-header page-header--full">
          <h1>API<span>s</span></h1>
          <div class="app-registration-link">
            <a href="{% url "apimanager:pre_login" %}" class="button">Register an application!</a>
          </div>
        </div>
      </div>
      {% if apis %}
      <div class="project-index">
      {% for api in apis %}
        <div class="layout-project-index-item">
          <div class="project-index-item">
            <div class="project-index-item__content">
            <a href="{% pageurl api %}">
              <div class="project-status project-status--{{api.status}}">{{api.get_status_display}}</div>
            <div class="project-index-image">
              {% if api.image %}
              {% image api.image fill-400x250 as image %}
              <div class="project-index-image" style="background-image: url({{image.url}})">{{project.image.title}}</div>
              {% else %}
               <div class="project-index-image" style="background-image: url({% static "images/api-image-default.png" %})">Default project image</div>
              {% endif %}
              </div>
            <h2>{{api.title}}</h2></a>
            <div class="project-description">{{api.short_description}}</div>
            </div>
        </div>
        </div>
      {% endfor %}
        </div>
      {% endif %}

</div>
{% endwith %}
{% endblock %}

apimanager/templates/apimanager/api_page.html
{% extends "base.html" %}

{% load static wagtailcore_tags %}

{% block extra_js %}
{% if self.has_swagger_docs %}
<link rel="stylesheet" href="https://unpkg.com/swagger-ui-dist@3.20.9/swagger-ui.css">
<script src="https://unpkg.com/swagger-ui-dist@3.20.9/swagger-ui-bundle.js"></script>
<script>

  const ui = SwaggerUIBundle({
    url: "{{ self.documentation }}",
    dom_id: "#swagger-ui-container"
  })
</script>
{% endif %}
{% endblock %}

{% block body_class %}swagger-section{% endblock %}

{% block content %}

    <div class="layout-page-content--full">
      <div class="page-content">
        <div class="page-content__box">
          <div>
            <a href="{% url "apimanager:pre_login" %}" class="button">Register an application!</a>
          </div>
          <h5 class="page-section-header">Open APIs</h5>
          <header>
            <h2>{{ self.title }}</h2>
            <p class="api-details__short-description">{{ self.short_description }}</p>
            <p class="api-details__location">API location: <a href="{{ self.api_url }}">{{ self.api_url }}</a></p>
          </header>
          <div class="api-details__description">{{ self.full_description|richtext }}</div>

{% if self.has_swagger_docs %}
          <div class="api-explorer">
            <h3>Explore the API</h3>
            <div class='input'><input placeholder="api_key" id="input_apiKey" name="apiKey" type="text"/></div>
            <div id="message-bar" class="swagger-ui-wrap" data-sw-translate>&nbsp;</div>
            <div id="swagger-ui-container" class="swagger-ui-wrap"></div>
          </div>
{% elif self.documentation %}
          <div class="api-explorer">
            <h3><a href="{{ self.documentation }}">Follow this link for API documentation</a></h3>
          </div>
{% endif %}
        </div>
      </div>
    </div>

{%  endblock %}

apimanager/templates/apimanager/pre_login_page.html
{% extends "base.html" %}
{% load wagtailcore_tags home_tags %}
{% block content %}
<div class="layout-page-content--full">
  <div class="page-content">
    <div class="page-content__box">
            <h1 class="page-section-header">Applications</h1>
            <p>
                You need to create a developer account with your Github (coming soon) or Facebook account before you can register your application.
            </p>
            <p>
                By registering your application, you can subscribe to <b>our Open APIs</b> and receive <b>API keys</b>.</p>
            <p>
                <a href="{% url "apimanager:add_application" %}" class="button">Register an application!</a>
            </p>

        </div>
    </div>
</div>
{% endblock %}